export interface LessonConfig {
  id: string;
  title: string;
  mdxPath: string;
  position: { row: number; column: number };
  prerequisites: string[];
  linkedHomeworks: string[];
  linkedTests: string[];
  linkedChains: string[];
}

export const contentConfig: LessonConfig[] = [
  {
    id: 'lesson_1',
    title: 'Введение',
    mdxPath: '/src/content/lectures/introductionLecture.md',
    position: { row: 0, column: 2 },
    prerequisites: [],
    linkedHomeworks: ['hw_intro_1', 'hw_intro_2', 'hw_intro_3'],
    linkedTests: ['test1'],
    linkedChains: [],
  },
  {
    id: 'lesson_2',
    title: 'Подготовка тела',
    mdxPath: '/src/content/lectures/bodyLecture.md',
    position: { row: 1, column: 2 },
    prerequisites: ['lesson_1'],
    linkedHomeworks: ['hw_body_1', 'hw_body_2', 'hw_body_3'],
    linkedTests: ['test2'],
    linkedChains: ['chain1'],
  },
  {
    id: 'lesson_3',
    title: 'Дыхание и опора',
    mdxPath: '/src/content/lectures/breathLecture.md',
    position: { row: 2, column: 2 },
    prerequisites: ['lesson_2'],
    linkedHomeworks: ['hw_breath_1', 'hw_breath_2', 'hw_breath_3'],
    linkedTests: ['test3'],
    linkedChains: ['chain2'],
  },
  {
    id: 'lesson_4',
    title: 'Лип-трилл',
    mdxPath: '/src/content/lectures/lipTrillLecture.md',
    position: { row: 3, column: 1 },
    prerequisites: ['lesson_3'],
    linkedHomeworks: ['hw_lip_1', 'hw_lip_2'],
    linkedTests: ['test4'],
    linkedChains: ['chain3'],
  },
  {
    id: 'lesson_5',
    title: 'Ритм',
    mdxPath: '/src/content/lectures/beatLecture.md',
    position: { row: 3, column: 2 },
    prerequisites: ['lesson_3'],
    linkedHomeworks: ['hw_beat_1', 'hw_beat_2', 'hw_beat_3', 'hw_beat_4', 'hw_beat_5'],
    linkedTests: ['test5'],
    linkedChains: [],
  },
  {
    id: 'lesson_6',
    title: 'Нотная грамота',
    mdxPath: '/src/content/lectures/notaLecture.md',
    position: { row: 3, column: 3 },
    prerequisites: ['lesson_3'],
    linkedHomeworks: ['hw_not_1', 'hw_not_2', 'hw_not_3'],
    linkedTests: ['test6'],
    linkedChains: [],
  },
  {
    id: 'lesson_7',
    title: 'Регистры голоса',
    mdxPath: '/src/content/lectures/registersLecture.md',
    position: { row: 4, column: 1 },
    prerequisites: ['lesson_4'],
    linkedHomeworks: [
      'hw_register_1',
      'hw_register_2',
      'hw_register_3',
      'hw_register_4',
      'hw_register_5',
    ],
    linkedTests: ['test7'],
    linkedChains: [],
  },
  {
    id: 'lesson_8',
    title: 'Унисон',
    mdxPath: '/src/content/lectures/unisonLecture.md',
    position: { row: 4, column: 3 },
    prerequisites: ['lesson_6'],
    linkedHomeworks: ['hw_un_1', 'hw_un_2'],
    linkedTests: ['test8'],
    linkedChains: [],
  },
  {
    id: 'lesson_9',
    title: 'Интервалы',
    mdxPath: '/src/content/lectures/intervalsLecture.md',
    position: { row: 5, column: 3 },
    prerequisites: ['lesson_8'],
    linkedHomeworks: [
      'hw_int_1',
      'hw_int_2',
      'hw_int_3',
      'hw_int_4',
      'hw_int_5',
      'hw_int_6',
      'hw_int_7',
      'hw_int_8',
    ],
    linkedTests: ['test9'],
    linkedChains: ['chain5'],
  },
  {
    id: 'lesson_10',
    title: 'Артикуляция и дикция',
    mdxPath: '/src/content/lectures/articulationLecture.md',
    position: { row: 6, column: 2 },
    prerequisites: ['lesson_7', 'lesson_9'],
    linkedHomeworks: [
      'hw_art_1',
      'hw_art_2',
      'hw_art_3',
      'hw_art_4',
      'hw_art_5',
      'hw_art_6',
      'hw_art_7',
      'hw_art_8',
      'hw_art_9',
    ],
    linkedTests: ['test10'],
    linkedChains: ['chain4'],
  },
  {
    id: 'lesson_11',
    title: 'Вокальные режимы',
    mdxPath: '/src/content/lectures/regimeLecture.md',
    position: { row: 7, column: 1 },
    prerequisites: ['lesson_10'],
    linkedHomeworks: ['hw_regime_1', 'hw_regime_2', 'hw_regime_3', 'hw_regime_4', 'hw_regime_5'],
    linkedTests: ['test11'],
    linkedChains: [],
  },
  {
    id: 'lesson_12',
    title: 'Вокальные украшения',
    mdxPath: '/src/content/lectures/decorationsLecture.md',
    position: { row: 7, column: 2 },
    prerequisites: ['lesson_10'],
    linkedHomeworks: ['hw_decor_1', 'hw_decor_2', 'hw_decor_3', 'hw_decor_4'],
    linkedTests: ['test12'],
    linkedChains: [],
  },
  {
    id: 'lesson_13',
    title: 'Расщепление',
    mdxPath: '/src/content/lectures/splittingLecture.md',
    position: { row: 7, column: 3 },
    prerequisites: ['lesson_10'],
    linkedHomeworks: ['hw_split_1'],
    linkedTests: ['test13'],
    linkedChains: [],
  },
  {
    id: 'lesson_14',
    title: 'Вокальная фразировка',
    mdxPath: '/src/content/lectures/phrasingLecture.md',
    position: { row: 8, column: 2 },
    prerequisites: ['lesson_11', 'lesson_12', 'lesson_13'],
    linkedHomeworks: ['hw_phras_1', 'hw_phras_2', 'hw_phras_3'],
    linkedTests: ['test14'],
    linkedChains: [],
  },
  {
    id: 'lesson_15',
    title: 'Динамика',
    mdxPath: '/src/content/lectures/dinamicLecture.md',
    position: { row: 9, column: 2 },
    prerequisites: ['lesson_14'],
    linkedHomeworks: ['hw_din_1', 'hw_din_2', 'hw_din_3'],
    linkedTests: ['test15'],
    linkedChains: [],
  },
  {
    id: 'lesson_16',
    title: 'Сторителлинг',
    mdxPath: '/src/content/lectures/storytellingLecture.md',
    position: { row: 10, column: 2 },
    prerequisites: ['lesson_15'],
    linkedHomeworks: ['hw_story_1', 'hw_story_2'],
    linkedTests: ['test16'],
    linkedChains: ['chain6'],
  },
  {
    id: 'lesson_17',
    title: 'Искусство работы с микрофоном',
    mdxPath: '/src/content/lectures/microphoneLecture.md',
    position: { row: 11, column: 2 },
    prerequisites: ['lesson_16'],
    linkedHomeworks: ['hw_micro_1'],
    linkedTests: ['test17'],
    linkedChains: [],
  },

  {
    id: 'lesson_3',
    title: 'Ритм',
    mdxPath: '/src/content/lesson_3.mdx',
    position: { row: 1, column: 2 },
    prerequisites: ['lesson_1'],
    linkedHomeworks: ['hw_rhythm_1', 'hw_rhythm_2'],
    linkedTests: ['test_rhythm'],
    linkedChains: ['chain_2'],
  },
  {
    id: 'lesson_4',
    title: 'Путь',
    mdxPath: '/src/content/lesson_4.mdx',
    position: { row: 1, column: 4 },
    prerequisites: ['lesson_1'],
    linkedHomeworks: ['hw_path_1'],
    linkedTests: [],
    linkedChains: ['chain_3'],
  },
  {
    id: 'lesson_5',
    title: 'Интервалы',
    mdxPath: '/src/content/lesson_5.mdx',
    position: { row: 2, column: 2 },
    prerequisites: ['lesson_2', 'lesson_3', 'lesson_4'],
    linkedHomeworks: ['hw_intervals_1', 'hw_intervals_2', 'hw_intervals_3'],
    linkedTests: ['test_intervals'],
    linkedChains: [],
  },
  {
    id: 'lesson_6',
    title: 'Аккорды',
    mdxPath: '/src/content/lesson_6.mdx',
    position: { row: 3, column: 2 },
    prerequisites: ['lesson_5'],
    linkedHomeworks: ['hw_chords_1', 'hw_chords_2'],
    linkedTests: [],
    linkedChains: [],
  },
  {
    id: 'lesson_7',
    title: 'Вокал',
    mdxPath: '/src/content/lesson_7.mdx',
    position: { row: 4, column: 2 },
    prerequisites: ['lesson_6'],
    linkedHomeworks: ['hw_vocal_1', 'hw_vocal_2'],
    linkedTests: ['test_final'],
    linkedChains: ['chain_final'],
  },
];
